global.helpers  = require('./helpers')
global.bittrex  = require('./exchange/bittrex')
global.poloniex = require('./exchange/poloniex')
global.analysis = require('./analysis')
global.Bot      = require('./bot')
